In [32]:
import numpy as np
import pandas as pd
import sklearn

data = pd.read_csv('Jan_2019_ontime.csv')

In [33]:
data.head(10)

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID  \
0             1            2                9E                  20363   
1             1            2                9E                  20363   
2             1            2                9E                  20363   
3             1            2                9E                  20363   
4             1            2                9E                  20363   
5             1            2                9E                  20363   
6             1            2                9E                  20363   
7             1            2                9E                  20363   
8             1            2                9E                  20363   
9             1            2                9E                  20363   

  OP_CARRIER TAIL_NUM  OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  \
0         9E   N8688C               3280              11953    GNV   
1         9E   N348PQ               3281              13487    MSP   
2         9E   N8896A               3282              11433    DTW   
3         9E   N8886A               3283              15249    TLH   
4         9E   N8974C               3284              10397    ATL   
5         9E   N927EV               3285              11267    DAY   
6         9E   N915XJ               3286              12448    JAN   
7         9E   N295PQ               3287              12953    LGA   
8         9E   N337PQ               3288              12451    JAX   
9         9E   N311PQ               3289              10397    ATL   

   DEST_AIRPORT_ID DEST  DEP_TIME  DEP_DEL15 DEP_TIME_BLK  ARR_TIME  \
0            10397  ATL     601.0        0.0    0600-0659     722.0   
1            11193  CVG    1359.0        0.0    1400-1459    1633.0   
2            11193  CVG    1215.0        0.0    1200-1259    1329.0   
3            10397  ATL    1521.0        0.0    1500-1559    1625.0   
4            11778  FSM    1847.0        0.0    1900-1959    1940.0   
5            13487  MSP     853.0        0.0    0900-0959     953.0   
6            10397  ATL    1553.0        0.0    1500-1559    1832.0   
7            11193  CVG    1551.0        0.0    1500-1559    1824.0   
8            12953  LGA    1037.0        0.0    1000-1059    1239.0   
9            10685  BMI    1245.0        0.0    1200-1259    1318.0   

   ARR_DEL15  CANCELLED  DIVERTED  DISTANCE  
0        0.0          0         0       300  
1        0.0          0         0       596  
2        0.0          0         0       229  
3        0.0          0         0       223  
4        0.0          0         0       579  
5        0.0          0         0       574  
6        0.0          0         0       341  
7        0.0          0         0       585  
8        0.0          0         0       833  
9        0.0          0         0       533

In [34]:
data.tail(10)

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID  \
583975            31            4                UA                  19977   
583976            31            4                UA                  19977   
583977            31            4                UA                  19977   
583978            31            4                UA                  19977   
583979            31            4                UA                  19977   
583980            31            4                UA                  19977   
583981            31            4                UA                  19977   
583982            31            4                UA                  19977   
583983            31            4                UA                  19977   
583984            31            4                UA                  19977   

       OP_CARRIER TAIL_NUM  OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  \
583975         UA   N813UA                205              14771    SFO   
583976         UA   N75861                204              13930    ORD   
583977         UA   N39728                203              10693    BNA   
583978         UA   N779UA                202              13930    ORD   
583979         UA   N769UA                201              12173    HNL   
583980         UA   N776UA                200              12016    GUM   
583981         UA   N36280                174              12016    GUM   
583982         UA   N36280                117              14955    SPN   
583983         UA   N39726                105              14955    SPN   
583984         UA   N39726                104              12016    GUM   

        DEST_AIRPORT_ID DEST  DEP_TIME  DEP_DEL15 DEP_TIME_BLK  ARR_TIME  \
583975            14057  PDX     604.0        0.0    0600-0659     802.0   
583976            12892  LAX     813.0        1.0    0700-0759    1028.0   
583977            12266  IAH    1105.0        0.0    1100-1159    1335.0   
583978            13830  OGG    1027.0        1.0    1000-1059    1457.0   
583979            12016  GUM    1502.0        0.0    1500-1559    1849.0   
583980            12173  HNL     749.0        0.0    0700-0759    1832.0   
583981            14955  SPN     717.0        0.0    0700-0759     759.0   
583982            12016  GUM     857.0        0.0    0900-0959     933.0   
583983            12016  GUM    1820.0        0.0    1800-1859    1854.0   
583984            14955  SPN    1636.0        0.0    1600-1659    1719.0   

        ARR_DEL15  CANCELLED  DIVERTED  DISTANCE  
583975        0.0          0         0       550  
583976        0.0          0         0      1744  
583977        1.0          0         0       657  
583978        0.0          0         0      4184  
583979        0.0          0         0      3801  
583980        0.0          0         0      3801  
583981        0.0          0         0       129  
583982        0.0          0         0       129  
583983        0.0          0         0       129  
583984        0.0          0         0       129

In [35]:
data.shape

(583985, 19)

In [36]:
data.columns

Index(['DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER',
       'OP_CARRIER_AIRLINE_ID', 'OP_CARRIER', 'TAIL_NUM', 'OP_CARRIER_FL_NUM',
       'ORIGIN_AIRPORT_ID', 'ORIGIN', 'DEST_AIRPORT_ID', 'DEST', 'DEP_TIME',
       'DEP_DEL15', 'DEP_TIME_BLK', 'ARR_TIME', 'ARR_DEL15', 'CANCELLED',
       'DIVERTED', 'DISTANCE'],
      dtype='object')

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583985 entries, 0 to 583984
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   DAY_OF_MONTH           583985 non-null  int64  
 1   DAY_OF_WEEK            583985 non-null  int64  
 2   OP_UNIQUE_CARRIER      583985 non-null  object 
 3   OP_CARRIER_AIRLINE_ID  583985 non-null  int64  
 4   OP_CARRIER             583985 non-null  object 
 5   TAIL_NUM               581442 non-null  object 
 6   OP_CARRIER_FL_NUM      583985 non-null  int64  
 7   ORIGIN_AIRPORT_ID      583985 non-null  int64  
 8   ORIGIN                 583985 non-null  object 
 9   DEST_AIRPORT_ID        583985 non-null  int64  
 10  DEST                   583985 non-null  object 
 11  DEP_TIME               567633 non-null  float64
 12  DEP_DEL15              567630 non-null  float64
 13  DEP_TIME_BLK           583985 non-null  object 
 14  ARR_TIME               566924 non-nu

In [38]:
data.isnull().sum()

DAY_OF_MONTH                 0
DAY_OF_WEEK                  0
OP_UNIQUE_CARRIER            0
OP_CARRIER_AIRLINE_ID        0
OP_CARRIER                   0
TAIL_NUM                  2543
OP_CARRIER_FL_NUM            0
ORIGIN_AIRPORT_ID            0
ORIGIN                       0
DEST_AIRPORT_ID              0
DEST                         0
DEP_TIME                 16352
DEP_DEL15                16355
DEP_TIME_BLK                 0
ARR_TIME                 17061
ARR_DEL15                18022
CANCELLED                    0
DIVERTED                     0
DISTANCE                     0
dtype: int64

In [39]:
column = ['OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'OP_CARRIER', 'TAIL_NUM', 'OP_CARRIER_FL_NUM', 'DEST', 'ORIGIN', 'DEP_TIME', 'DEP_DEL15', 'DEP_TIME_BLK', 'ARR_TIME', 'ARR_DEL15', 'DIVERTED', 'DISTANCE' ]

df = data.drop(columns = column)
df.head()

DAY_OF_MONTH  DAY_OF_WEEK  ORIGIN_AIRPORT_ID  DEST_AIRPORT_ID  CANCELLED
0             1            2              11953            10397          0
1             1            2              13487            11193          0
2             1            2              11433            11193          0
3             1            2              15249            10397          0
4             1            2              10397            11778          0

In [40]:
df.isnull().sum()

DAY_OF_MONTH         0
DAY_OF_WEEK          0
ORIGIN_AIRPORT_ID    0
DEST_AIRPORT_ID      0
CANCELLED            0
dtype: int64

In [41]:
array = df.values
X = array [:, 0:4]
Y = array [:, 4]
array

array([[    1,     2, 11953, 10397,     0],
       [    1,     2, 13487, 11193,     0],
       [    1,     2, 11433, 11193,     0],
       ...,
       [   31,     4, 14955, 12016,     0],
       [   31,     4, 14955, 12016,     0],
       [   31,     4, 12016, 14955,     0]], dtype=int64)

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
x_test

array([[   10,     4, 10397, 11057],
       [   24,     4, 15304, 14122],
       [   19,     6, 14771, 11618],
       ...,
       [   12,     6, 13495, 12266],
       [   15,     2, 11259, 14107],
       [   29,     2, 11298, 13891]], dtype=int64)

In [43]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()
modelnb.fit(x_train, y_train)

GaussianNB()

In [44]:
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([453797.,  13391.])

In [45]:
y_pred = nbtrain.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
np.array(y_test)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [47]:
nbtrain.predict_proba(x_test)

array([[0.99007748, 0.00992252],
       [0.94683603, 0.05316397],
       [0.96712535, 0.03287465],
       ...,
       [0.98344334, 0.01655666],
       [0.97694016, 0.02305984],
       [0.935851  , 0.064149  ]])